import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';

test('Postgres RLS protects originals, drafts, membership and publication slots',async t=>{
  const db=new PGlite();t.after(()=>db.close());
  await db.exec(`
    create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth; create schema storage;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    grant usage on schema auth,storage,public to anon,authenticated,service_role;
    grant execute on function auth.uid() to anon,authenticated,service_role;
    create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
    create table storage.objects(id bigint generated always as identity,bucket_id text,name text);
    alter table storage.objects enable row level security;
    grant select,insert,update,delete on storage.objects to authenticated,anon;
    grant usage on sequence storage.objects_id_seq to authenticated;
    insert into auth.users values ('10000000-0000-4000-8000-000000000001'),('10000000-0000-4000-8000-000000000002');
  `);
  await db.exec(await readFile('infra/gallery-schema.sql','utf8'));
  await db.exec(await readFile('infra/video-schema.sql','utf8'));
  await db.exec(`insert into public.gallery_admins values ('10000000-0000-4000-8000-000000000001');`);
  const identity=async (role,id='')=>db.exec(`reset role; select set_config('request.jwt.claim.sub','${id}',false); set role ${role};`);
  await identity('anon');
  await assert.rejects(db.query('select * from public.gallery_artworks'));
  assert.equal((await db.query('select * from storage.objects')).rows.length,0);
  await identity('authenticated','10000000-0000-4000-8000-000000000002');
  assert.equal((await db.query('select * from public.gallery_admins')).rows.length,0);
  assert.equal((await db.query('select * from public.gallery_videos')).rows.length,0);
  await assert.rejects(db.query(`insert into public.gallery_admins values ('10000000-0000-4000-8000-000000000002')`));
  await assert.rejects(db.query(`insert into storage.objects(bucket_id,name) values ('gallery-originals','x.jpg')`));
  await identity('authenticated','10000000-0000-4000-8000-000000000001');
  const id='20000000-0000-4000-8000-000000000001';
  await db.query(`insert into public.gallery_artworks(id,title,original_path,preview_path,width,height) values ($1,'Opera',$2,$3,1200,1800)`,[id,`${id}/original.jpg`,`${id}/preview.jpg`]);
  await assert.rejects(db.query(`update public.gallery_artworks set published=true where id=$1`,[id]));
  await db.query(`insert into storage.objects(bucket_id,name) values ('gallery-originals',$1),('gallery-previews',$2)`,[`${id}/original.jpg`,`${id}/preview.jpg`]);
  await db.query(`update public.gallery_artworks set published=true where id=$1`,[id]);
  const row=(await db.query('select * from public.gallery_artworks')).rows[0];
  assert.equal(row.hall_index,0);assert.equal(row.wall_slot,0);
  await db.query(`delete from storage.objects where name=$1`,[`${id}/original.jpg`]);
  assert.equal((await db.query('select * from storage.objects')).rows.length,2,'Referenced originals cannot be deleted');
  await identity('authenticated','10000000-0000-4000-8000-000000000002');
  assert.equal((await db.query('select * from public.gallery_artworks')).rows.length,0);
  assert.equal((await db.query('select * from storage.objects')).rows.length,0);
  await db.query('update public.gallery_artworks set published=false');
  await identity('authenticated','10000000-0000-4000-8000-000000000001');
  assert.equal((await db.query('select published from public.gallery_artworks')).rows[0].published,true);
  await db.query('update public.gallery_artworks set published=false');
  assert.equal((await db.query('select published from public.gallery_artworks')).rows[0].published,false);
  assert.equal((await db.query('select * from storage.objects')).rows.length,2);
  const clip='30000000-0000-4000-8000-000000000001';
  await db.query(`insert into public.gallery_videos(id,title,video_path,preview_path,width,height,duration) values($1,'Clip',$2,$3,1920,1080,20)`,[clip,`${clip}/clip.mp4`,`${clip}/poster.jpg`]);
  await assert.rejects(db.query('update public.gallery_videos set published=true'));
  await db.query(`insert into storage.objects(bucket_id,name) values('gallery-videos',$1),('gallery-previews',$2)`,[`${clip}/clip.mp4`,`${clip}/poster.jpg`]);
  await db.query('update public.gallery_videos set published=true');
  assert.equal((await db.query('select published from public.gallery_videos')).rows[0].published,true);
  await db.query(`delete from storage.objects where name=$1`,[`${clip}/poster.jpg`]);
  assert.equal((await db.query('select * from storage.objects')).rows.length,4);
});
